language: bash
services: docker

env:
  - VERSION=3.6 VARIANT=debian

before_script:
  - cd "$VERSION/$VARIANT/"
  - image="$(awk 'toupper($1) == "FROM" { print $2; exit }' management/Dockerfile)"


script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t "teknique/$image" teknique/
  - docker push "teknique/${image}"
  - docker build -t "teknique/${image}-management" management/teknique/
  - docker push "teknique/${image}-management"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
